#!/bin/sh -eu


# Your source directory. Default is the config dir, if it can be found.
SRC_DIR=

# Executable name, from the executable stanza of your cabal file.
EXE_NAME=my-xmonad

# Where will be the executable placed
INSTALL_DIR="$HOME/.cabal/bin"
##############################################################################

# config

output="$1"

if [ "$SRC_DIR" = "" ]; then
    # look for the config directory, fall back to the old one
    SRC_DIR="${XMONAD_CONFIG_DIR:-${XDG_CONFIG_HOME:-$HOME/.config/xmonad}}"
    if test -f "$SRC_DIR/build"; then
	:
    else
	SRC_DIR="$HOME/.xmonad"
    fi
fi

if [ "$INSTALL_DIR" = "" ]; then
    INSTALL_DIR = "$SRC_DIR"
fi

cd "$SRC_DIR"

for exe in $EXE_NAME; do
    cabal install exe:"$EXE_NAME" \
	  --enable-executable-stripping \
	  --enable-optimization=2 \
	  --installdir="$INSTALL_DIR" \
	  --overwrite-policy=always

    ln -sf "$INSTALL_DIR/$exe" "$output"
done